db:
  source:
    database: 'sync1'
    host: '192.168.0.238'
    port: 3306
    user: 'root'
    pwd: '123456789'
  target:
    database: 'sync2'
    host: '192.168.0.238'
    port: 3306
    user: 'root'
    pwd: '123456789'
